server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/mbtiapp?serverTimezone=UTC&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false'
    username: 'mbtiapp'
    password: 'mbtiapp'
    driver-class-name: com.mysql.cj.jdbc.Driver