server:
  port: 5000

spring:
  datasource:
    url: "jdbc:mysql://${DB_ENDPOINT}:3306/mbtiapp?serverTimezone=UTC&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver